# Generated by Django 3.2.9 on 2021-12-19 19:53

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120, verbose_name='Name')),
                ('second_name', models.CharField(max_length=120, verbose_name='Last Name')),
                ('father_name', models.CharField(max_length=120, verbose_name='Father`s Name')),
                ('pseudonym', models.CharField(max_length=120, verbose_name='Pseudonym')),
                ('date_birth', models.DateField()),
            ],
            managers=[
                ('author_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('address', models.CharField(max_length=120, verbose_name='Address')),
                ('foundation', models.DateField()),
            ],
            managers=[
                ('publisher_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('genre', models.CharField(max_length=60, verbose_name='Genre')),
                ('timestamp', models.DateField()),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.author')),
                ('id_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.publisher')),
            ],
            managers=[
                ('book_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
